# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Nganasan spellchecker"
nio = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Nganasan, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
nio = "TRANSLATE: A spellchecker for Nganasan, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.nio"

[windows]
system_product_code = "{D8405FAA-04E5-4EB5-ABA8-C3EEF30EF4B1}_is1"
legacy_product_codes = [
    { value = "3AA74247-088E-46D3-AEF5-C1E7FA587799", kind = "nsis" },
    { value = "AF5ED7AB-E77E-48F3-8ABC-23ABDB873FF0", kind = "nsis" }
]

[package.speller]
name = "Nganasan"
version = "0.1.1"

[package.grammar]
name = "Nganasan"
version = "0.1.0"

[package.tts-text-proc]
name = "Nganasan"
version = "0.1.0"

[package.hyphenator]
name = "Nganasan"
version = "0.1.0"
