template = "https://github.com/giellalt/template-lang-und"
rev_id = 261
template_sha = "eaa0621ef7403d653282fabf176060ed3c95ebf4"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
