template = "https://github.com/giellalt/template-lang-und"
rev_id = 258
template_sha = "b5271fc37dc1cf0a7448e0553c24b3f857121d34"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
