template = "https://github.com/giellalt/template-lang-und"
rev_id = 269
template_sha = "c43b39fe5507de4cc3a96e60743ab44578e61fd2"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
