template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "ngan1291"
__REPO__ = "lang-nio"
__UND2C__ = "nio"
__UNDEFINED__ = "Nganasan"
__UND__ = "nio"
